baseURL = 'https://nonentitydev.githubpages.com/'
languageCode = 'en-us'
title = 'NonEntity'
theme = 'mini'

[params]
subTitle = 'Where I code for fun.'

[caches]
    [caches.images]
        dir = ':cacheDir/images'
