baseURL = 'https://nonentitydev.githubpages.com/'
languageCode = 'en-us'
title = 'NonEntity'
theme = 'mini'


[params]
subTitle = 'Where I code for fun.'
avatarImage = '/images/nonentity_logo_black.png'

[caches]
    [caches.images]
        dir = ':cacheDir/images'
